### ISSUE TITLE
您可以在此发布您所提供的公益qsign

### ISSUE THREAD

**Issue by rhwong** [rhwong/onekey-issue#1]
请按照以下格式登记
```
API: https://loli.band
KEY: None
ANDROID_ID: 1ab2c3d4e5 //若qsign_version高于1.1.1，则无需此项
tx_lib_version: 8.9.63
qsign_version: 1.1.0
Owner: 贰狐
INFO: 此API为1.1.0的API，用于测试，随时重启，切勿使用。
```
请根据您的服务器配置，斟酌是否公开此API，若后续需要下架或暂停接入，请回复原评论关闭此API启用。
鼓励您在服务器性能足够的情况下分享API供其他人使用，但是在保证您利益的前提下，请尽可能维持其稳定性。
我不会主动收集其他地方公开的API进行展示，但是您可以在看到后，在此issue中引用，以供其他人选择。
发布地址：https://qsign.dev/

**Comment by Chenshengm** [comment]
收到啦＿＿
